################################################################################
# Automatically-generated file. Do not edit!
################################################################################

S79_SRCS := 
C++M_SRCS := 
ASM_SRCS := 
CPP_SRCS := 
S79_UPPER_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
CCM_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CXXM_SRCS := 
CC_DEPS := 
C++_DEPS := 
CCM_DEPS := 
EXECUTABLES := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
CXXM_DEPS := 
C++M_DEPS := 
C_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Driver/lvgl/demos/benchmark/assets \
Driver/lvgl/demos/benchmark \
Driver/lvgl/demos/flex_layout \
Driver/lvgl/demos/keypad_encoder \
Driver/lvgl/demos \
Driver/lvgl/demos/multilang/assets/avatars \
Driver/lvgl/demos/multilang/assets/emojis \
Driver/lvgl/demos/multilang/assets/fonts \
Driver/lvgl/demos/multilang/assets \
Driver/lvgl/demos/multilang \
Driver/lvgl/demos/music/assets \
Driver/lvgl/demos/music \
Driver/lvgl/demos/render/assets \
Driver/lvgl/demos/render \
Driver/lvgl/demos/scroll \
Driver/lvgl/demos/stress \
Driver/lvgl/demos/transform/assets \
Driver/lvgl/demos/transform \
Driver/lvgl/demos/vector_graphic/assets \
Driver/lvgl/demos/vector_graphic \
Driver/lvgl/demos/widgets/assets \
Driver/lvgl/demos/widgets \
Driver/lvgl/env_support/pikascript \
Driver/lvgl/env_support/rt-thread \
Driver/lvgl/env_support/rt-thread/squareline \
Driver/lvgl/examples/anim \
Driver/lvgl/examples/assets \
Driver/lvgl/examples/assets/emoji \
Driver/lvgl/examples/event \
Driver/lvgl/examples/get_started \
Driver/lvgl/examples/layouts/flex \
Driver/lvgl/examples/layouts/grid \
Driver/lvgl/examples/libs/barcode \
Driver/lvgl/examples/libs/bmp \
Driver/lvgl/examples/libs/ffmpeg \
Driver/lvgl/examples/libs/freetype \
Driver/lvgl/examples/libs/gif \
Driver/lvgl/examples/libs/libjpeg_turbo \
Driver/lvgl/examples/libs/libpng \
Driver/lvgl/examples/libs/lodepng \
Driver/lvgl/examples/libs/qrcode \
Driver/lvgl/examples/libs/rlottie \
Driver/lvgl/examples/libs/tiny_ttf \
Driver/lvgl/examples/libs/tjpgd \
Driver/lvgl/examples/others/file_explorer \
Driver/lvgl/examples/others/fragment \
Driver/lvgl/examples/others/gridnav \
Driver/lvgl/examples/others/ime \
Driver/lvgl/examples/others/imgfont \
Driver/lvgl/examples/others/monkey \
Driver/lvgl/examples/others/observer \
Driver/lvgl/examples/others/snapshot \
Driver/lvgl/examples/porting \
Driver/lvgl/examples/porting/osal \
Driver/lvgl/examples/scroll \
Driver/lvgl/examples/styles \
Driver/lvgl/examples/widgets/animimg \
Driver/lvgl/examples/widgets/arc \
Driver/lvgl/examples/widgets/bar \
Driver/lvgl/examples/widgets/button \
Driver/lvgl/examples/widgets/buttonmatrix \
Driver/lvgl/examples/widgets/calendar \
Driver/lvgl/examples/widgets/canvas \
Driver/lvgl/examples/widgets/chart \
Driver/lvgl/examples/widgets/checkbox \
Driver/lvgl/examples/widgets/dropdown \
Driver/lvgl/examples/widgets/image \
Driver/lvgl/examples/widgets/imagebutton \
Driver/lvgl/examples/widgets/keyboard \
Driver/lvgl/examples/widgets/label \
Driver/lvgl/examples/widgets/led \
Driver/lvgl/examples/widgets/line \
Driver/lvgl/examples/widgets/list \
Driver/lvgl/examples/widgets/lottie \
Driver/lvgl/examples/widgets/menu \
Driver/lvgl/examples/widgets/msgbox \
Driver/lvgl/examples/widgets/obj \
Driver/lvgl/examples/widgets/roller \
Driver/lvgl/examples/widgets/scale \
Driver/lvgl/examples/widgets/slider \
Driver/lvgl/examples/widgets/span \
Driver/lvgl/examples/widgets/spinbox \
Driver/lvgl/examples/widgets/spinner \
Driver/lvgl/examples/widgets/switch \
Driver/lvgl/examples/widgets/table \
Driver/lvgl/examples/widgets/tabview \
Driver/lvgl/examples/widgets/textarea \
Driver/lvgl/examples/widgets/tileview \
Driver/lvgl/examples/widgets/win \
Driver/lvgl/src/core \
Driver/lvgl/src/display \
Driver/lvgl/src/draw \
Driver/lvgl/src/draw/nxp/pxp \
Driver/lvgl/src/draw/nxp/vglite \
Driver/lvgl/src/draw/renesas/dave2d \
Driver/lvgl/src/draw/sdl \
Driver/lvgl/src/draw/sw/blend/helium \
Driver/lvgl/src/draw/sw/blend \
Driver/lvgl/src/draw/sw/blend/neon \
Driver/lvgl/src/draw/sw \
Driver/lvgl/src/draw/vg_lite \
Driver/lvgl/src/drivers/display/drm \
Driver/lvgl/src/drivers/display/fb \
Driver/lvgl/src/drivers/display/ili9341 \
Driver/lvgl/src/drivers/display/lcd \
Driver/lvgl/src/drivers/display/renesas_glcdc \
Driver/lvgl/src/drivers/display/st7735 \
Driver/lvgl/src/drivers/display/st7789 \
Driver/lvgl/src/drivers/display/st7796 \
Driver/lvgl/src/drivers/display/tft_espi \
Driver/lvgl/src/drivers/evdev \
Driver/lvgl/src/drivers/glfw \
Driver/lvgl/src/drivers/libinput \
Driver/lvgl/src/drivers/nuttx \
Driver/lvgl/src/drivers/qnx \
Driver/lvgl/src/drivers/sdl \
Driver/lvgl/src/drivers/wayland \
Driver/lvgl/src/drivers/windows \
Driver/lvgl/src/drivers/x11 \
Driver/lvgl/src/font \
Driver/lvgl/src/indev \
Driver/lvgl/src/layouts/flex \
Driver/lvgl/src/layouts/grid \
Driver/lvgl/src/layouts \
Driver/lvgl/src/libs/barcode \
Driver/lvgl/src/libs/bin_decoder \
Driver/lvgl/src/libs/bmp \
Driver/lvgl/src/libs/ffmpeg \
Driver/lvgl/src/libs/freetype \
Driver/lvgl/src/libs/fsdrv \
Driver/lvgl/src/libs/gif \
Driver/lvgl/src/libs/libjpeg_turbo \
Driver/lvgl/src/libs/libpng \
Driver/lvgl/src/libs/lodepng \
Driver/lvgl/src/libs/lz4 \
Driver/lvgl/src/libs/qrcode \
Driver/lvgl/src/libs/rle \
Driver/lvgl/src/libs/rlottie \
Driver/lvgl/src/libs/thorvg \
Driver/lvgl/src/libs/tiny_ttf \
Driver/lvgl/src/libs/tjpgd \
Driver/lvgl/src \
Driver/lvgl/src/misc/cache \
Driver/lvgl/src/misc \
Driver/lvgl/src/osal \
Driver/lvgl/src/others/file_explorer \
Driver/lvgl/src/others/fragment \
Driver/lvgl/src/others/gridnav \
Driver/lvgl/src/others/ime \
Driver/lvgl/src/others/imgfont \
Driver/lvgl/src/others/monkey \
Driver/lvgl/src/others/observer \
Driver/lvgl/src/others/snapshot \
Driver/lvgl/src/others/sysmon \
Driver/lvgl/src/others/vg_lite_tvg \
Driver/lvgl/src/stdlib/builtin \
Driver/lvgl/src/stdlib/clib \
Driver/lvgl/src/stdlib \
Driver/lvgl/src/stdlib/micropython \
Driver/lvgl/src/stdlib/rtthread \
Driver/lvgl/src/themes/default \
Driver/lvgl/src/themes \
Driver/lvgl/src/themes/mono \
Driver/lvgl/src/themes/simple \
Driver/lvgl/src/tick \
Driver/lvgl/src/widgets/animimage \
Driver/lvgl/src/widgets/arc \
Driver/lvgl/src/widgets/bar \
Driver/lvgl/src/widgets/button \
Driver/lvgl/src/widgets/buttonmatrix \
Driver/lvgl/src/widgets/calendar \
Driver/lvgl/src/widgets/canvas \
Driver/lvgl/src/widgets/chart \
Driver/lvgl/src/widgets/checkbox \
Driver/lvgl/src/widgets/dropdown \
Driver/lvgl/src/widgets/image \
Driver/lvgl/src/widgets/imagebutton \
Driver/lvgl/src/widgets/keyboard \
Driver/lvgl/src/widgets/label \
Driver/lvgl/src/widgets/led \
Driver/lvgl/src/widgets/line \
Driver/lvgl/src/widgets/list \
Driver/lvgl/src/widgets/lottie \
Driver/lvgl/src/widgets/menu \
Driver/lvgl/src/widgets/msgbox \
Driver/lvgl/src/widgets/objx_templ \
Driver/lvgl/src/widgets/property \
Driver/lvgl/src/widgets/roller \
Driver/lvgl/src/widgets/scale \
Driver/lvgl/src/widgets/slider \
Driver/lvgl/src/widgets/span \
Driver/lvgl/src/widgets/spinbox \
Driver/lvgl/src/widgets/spinner \
Driver/lvgl/src/widgets/switch \
Driver/lvgl/src/widgets/table \
Driver/lvgl/src/widgets/tabview \
Driver/lvgl/src/widgets/textarea \
Driver/lvgl/src/widgets/tileview \
Driver/lvgl/src/widgets/win \
Driver/lvgl/tests/makefile \
Driver/lvgl/tests/makefile_uefi \
Driver/lvgl/tests/src \
Driver/lvgl/tests/src/test_assets \
Driver/lvgl/tests/src/test_cases \
Driver/lvgl/tests/src/test_cases/cache \
Driver/lvgl/tests/src/test_cases/draw \
Driver/lvgl/tests/src/test_cases/libs \
Driver/lvgl/tests/src/test_cases/widgets \
Driver/lvgl/tests/src/test_libs/rnd_unicodes \
Driver/lvgl/tests/src/test_libs/rnd_unicodes/rnd_unicodes/src \
Driver/lvgl/tests/test_images/stride_align1/LZ4 \
Driver/lvgl/tests/test_images/stride_align1/RLE \
Driver/lvgl/tests/test_images/stride_align1/UNCOMPRESSED \
Driver/lvgl/tests/test_images/stride_align64/LZ4 \
Driver/lvgl/tests/test_images/stride_align64/RLE \
Driver/lvgl/tests/test_images/stride_align64/UNCOMPRESSED \
Driver/lvgl/tests/unity \
. \
autogen \
simplicity_sdk_2025.6.3/hardware/board/src \
simplicity_sdk_2025.6.3/hardware/driver/configuration_over_swo/src \
simplicity_sdk_2025.6.3/hardware/driver/mic/src \
simplicity_sdk_2025.6.3/hardware/driver/mx25_flash_shutdown/src/sl_mx25_flash_shutdown_eusart \
simplicity_sdk_2025.6.3/platform/Device/SiliconLabs/EFR32MG26/Source \
simplicity_sdk_2025.6.3/platform/common/src \
simplicity_sdk_2025.6.3/platform/driver/debug/src \
simplicity_sdk_2025.6.3/platform/driver/gpio/src \
simplicity_sdk_2025.6.3/platform/emdrv/dmadrv/src \
simplicity_sdk_2025.6.3/platform/emdrv/spidrv/src \
simplicity_sdk_2025.6.3/platform/emlib/src \
simplicity_sdk_2025.6.3/platform/peripheral/src \
simplicity_sdk_2025.6.3/platform/service/clock_manager/src \
simplicity_sdk_2025.6.3/platform/service/device_init/src \
simplicity_sdk_2025.6.3/platform/service/device_manager/clocks \
simplicity_sdk_2025.6.3/platform/service/device_manager/devices \
simplicity_sdk_2025.6.3/platform/service/device_manager/src \
simplicity_sdk_2025.6.3/platform/service/interrupt_manager/src \
simplicity_sdk_2025.6.3/platform/service/iostream/src \
simplicity_sdk_2025.6.3/platform/service/memory_manager/src \
simplicity_sdk_2025.6.3/platform/service/sl_main/src \
simplicity_sdk_2025.6.3/platform/service/sleeptimer/src \
simplicity_sdk_2025.6.3/platform/service/udelay/src \
ui \

